### ISSUE TITLE
Odd warning message on XLOAD

### ISSUE THREAD

**Issue by e9gille** [mkromberg/link#6]
I ran the QA tests which passed successfully. After that I tried XLOADing a ws and saw the folowing warnings in the session:
```
      )xload C:\devt\svq\SVQ_12_124.dws
C:\devt\svq\SVQ_12_124.dws saved Tue Apr 12 11:33:15 2016
c:/src/trunk/SALT\core/Import.dyalog cannot be found
c:/src/trunk/SALT\core/Fix.dyalog cannot be found
c:/src/trunk/SALT\core/FileSystemWatcher.dyalog cannot be found
c:/src/trunk/SALT\core/Export.dyalog cannot be found
```

Any idea what causes this?

**Comment by mkromberg** [comment]
This is caused by a combination of an over-excited check in the interpreter, and probably some old links in your session object. It should be gone in the next APL build that you get.

**Comment by e9gille** [comment]
I just checked and can see that although I had replaced the SALT folder with the one you gave me before I launched D17 for the first time, it still has the old version of SALT loaded in the session.
I tried `⎕SE.SALT.Reboot''` but that crashed. How do I get the new version of SALT into the sesssion?

**Comment by e9gille** [comment]
No, my bad, it was the latest code after all...
